### Post a new film
POST http://localhost:3000/films
Content-Type: application/json

{
    "title": "Star Wars: The Phantom Menace (Episode I)",
    "duration": 300,
    "budget": 2000,
    "link": "lotr.com"
}